### ISSUE TITLE
RFE: tune specific devices only

### ISSUE THREAD

**Issue by jmoellers** [redhat-performance/tuned#106]
As we start to get more diverse devices (eg rotating vs solid-state disks), would it not make sense to be able to tune specific devices rather than entire devices classes?
Eg rather than [disk], maybe one would specify [disk:sda,sdc] or something to that tune (pun intended)?

**Comment by olysonek** [comment]
You can always specify which devices should be tuned in custom profiles. You can also create multiple instances of the `disk` plugin so that you can tune different devices differently, e.g.:
```
[disk_rotating]
type=disk
devices=sda,sdc
readahead=512

[disk_ssd]
type=disk
devices=sdb
readahead=64
```
Does that answer your question?

**Comment by jmoellers** [comment]
Yepp! 100% ... no ... AT LEAST 110% on the spot!
Thanks!
