### ISSUE TITLE
serial console setup

### ISSUE THREAD

**Issue by sghosh151** [redhat-performance/tuned#109]
While not directly a performance issue, it would be great if tuned could include options to set the GRUB boot option to include setting console=ttySX, 115200n8 

Most writeups recommend editing /etc/default/grub  - But that feels the wrong way to go.

eg: https://wiki.polaire.nl/doku.php?id=supermicro_-_centos7

**Comment by olysonek** [comment]
> While not directly a performance issue, it would be great if tuned could include options to set the GRUB boot option to include setting console=ttySX, 115200n8

You can already do that. For example create a custom profile with the following:
```
[bootloader]
cmdline=console=ttyS0,115200n8
```
That will modify `/etc/default/grub` and `/etc/grub2.cfg` (or `/etc/grub2-efi.cfg`) for you ;).

> Most writeups recommend editing /etc/default/grub - But that feels the wrong way to go.

It's not wrong. It's the best way there currently is as far as I'm aware.
