### ISSUE TITLE
plugin_net should use python-ethtool instead of ethtool

### ISSUE THREAD

**Issue by olysonek** [redhat-performance/tuned#115]
Currently the "net" plugin uses the ethtool command line tool to set parameters of network interfaces. This is problematic for several reasons: executing external tools has significant overhead, it is prone to errors as we need to parse the output of ethtool, and it makes proper error reporting difficult. It might be better to use the python module python-ethtool instead.

Note that I didn't actually investigate whether python-ethtool is suitable for our needs, but I think it's worth looking into.

**Comment by TomasKorbar** [comment]
Hi,
I looked onto this and this is what i found out. Python-ethtool module is no longer developed which means it would be difficult for us to keep up with the latest network card features. Its developer told me we should use netifaces but unfortunately it does not support setting network card features, so it is not suitable for us. From my point of view using ethtool and parsing its output is the easiest and the most maintainable way how to provide functionalities we need in tuned, at least for now.

**Comment by olysonek** [comment]
Thanks for looking into it. I think there's nothing else to be done here, closing.
