### ISSUE TITLE
grub boot problems with network-latency profile

### ISSUE THREAD

**Issue by dansiemon** [redhat-performance/tuned#117]
The network-latency profile wants to set the skew_tick kernel option. It looks like this is somehow causing boot problems - we've had this happen on a bunch of boxes now.

Grub boot stops at the grub> prompt. Manually selecting the kernel and initrd from the grub> prompt boots fine.

Looking at /boot/grub2/boot.cfg I see:

```
### BEGIN /etc/grub.d/00_tuned ###
set tuned_initrd=""
set tuned_params="skew_tick=1"=1"=1"=1"=1"=1"=1"=1"=1"=1"=1"=1"=1"=1"=1"=1"=1"=1"=1"=1"
### END /etc/grub.d/00_tuned ###
```

Trying to use the grub 'configfile' command with that grub.cfg complains about syntax errors. I'm not 100% sure the above is the cause but it's highly suspicious and likely a bug in any case.

**Comment by olysonek** [comment]
Is this Fedora? You are affected by
https://bugzilla.redhat.com/show_bug.cgi?id=1509515

I guess you'll need to edit the grub.cfg file manually so that the 'set tuned_params ...' line says:
`set tuned_params="skew_tick=1"`

You'll have to do that after each kernel update. Oh well...

**Comment by yarda** [comment]
@dansiemon as a temporal workaround you could comment the bootloader section in the tuned.conf. You will lost the skew_tick setting (you can patch it manually to grub.cfg), but it should help with this problem.

**Comment by olysonek** [comment]
Better manually add it to `GRUB_CMDLINE_LINUX` in `/etc/default/grub`, so that it gets automatically applied to new kernels.
