### ISSUE TITLE
can't install using the instructions in the INSTALL file

### ISSUE THREAD

**Issue by lovengulu** [redhat-performance/tuned#127]
I had two issues during the install:
1. Python's dmidecode is required. 
    I resolved by installing:
`	yum install python-pip

	pip install dmidecode
`

The proper solution is to add a requirements.txt file. 

2. can't run any of the installed executable. Example:
```
# tuned-adm
-bash: /usr/sbin/tuned-adm: python2: bad interpreter: No such file or directory
```
That's because the first line has:
`#!python2 -Es`
instead of 
`#!/usr/bin/python2 -Es`

I was able to workaround, but don't know how to solve it properly.  

Note:
I'm running centos7.5. It has python2 installed by default.

**Comment by yarda** [comment]
Do you install from RPM? Which RPM? CentOS? Could you provide version? In such case you shouldn't probably use PIP. If you use CentOS RPM it's probably problem in the CentOS RPM.

If you install by hand from the tarball, the interpreter should default to /usr/bin/python3, you can override by:
# make install PYTHON=/usr/bin/python2

**Comment by lovengulu** [comment]
I installed from a copy of the git repo. 
Issue 2 - resolved as you suggested.  I'll update the misleading INSTALL and issue a pull request. 
Issue 1 - I think I can do this as well.
Should both be on the same pull request or it is easier that I separate?

**Comment by yarda** [comment]
Thanks, do it the way which is the most comfortable for you.
