### ISSUE TITLE
TypeError: '>' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by Maryse47** [redhat-performance/tuned#148]
This is from latest git snapshot on Arch Linux:

```
tuned[14466]: --- Logging error ---
tuned[14466]: Traceback (most recent call last):
tuned[14466]:   File "/usr/lib/python3.7/logging/handlers.py", line 69, in emit
tuned[14466]:     self.doRollover()
tuned[14466]:   File "/usr/lib/python3.7/logging/handlers.py", line 158, in doRollover
tuned[14466]:     if self.backupCount > 0:
tuned[14466]: TypeError: '>' not supported between instances of 'str' and 'int'
tuned[14466]: Call stack:
tuned[14466]:   File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
tuned[14466]:     self._bootstrap_inner()
tuned[14466]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
tuned[14466]:     self.run()
tuned[14466]:   File "/usr/lib/python3.7/threading.py", line 865, in run
tuned[14466]:     self._target(*self._args, **self._kwargs)
tuned[14466]:   File "/usr/lib/python3.7/site-packages/tuned/exports/dbus_exporter.py", line 154, in _thread_code
tuned[14466]:     self._main_loop.run()
tuned[14466]:   File "/usr/lib/python3.7/site-packages/gi/overrides/GLib.py", line 498, in run
tuned[14466]:     super(MainLoop, self).run()
tuned[14466]:   File "/usr/lib/python3.7/site-packages/dbus/service.py", line 707, in _message_cb
tuned[14466]:     retval = candidate_method(self, *args, **keywords)
tuned[14466]:   File "<decorator-gen-16>", line 2, in verify_profile
tuned[14466]:   File "/usr/lib/python3.7/site-packages/tuned/exports/dbus_exporter.py", line 88, in wrapper
tuned[14466]:     return method(*args, **kwargs)
```

The app seems to work more or less ok (except gui) but it spams logs constantly with output as above. Full logs below. The package was build from https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tuned-git

[tuned.txt](https://github.com/redhat-performance/tuned/files/2747586/tuned.txt)

**Comment by yarda** [comment]
Thanks for the report. Unfortunately, I cannot see what's wrong from the traceback. Maybe there is something wrong in the arch python stack?

**Comment by yarda** [comment]
I am unable to reproduce the problem with python3-3.7.2 on Fedora 29. I tried the latest head: 26db89de18efad1b453618ea8156422d26e0c85f, which seems to be the same code which is in the arch. The problem is that the backrace ends outside of tuned, and in the last lines from the Tuned code, I cannot see nothing suspicious.

**Comment by Maryse47** [comment]
I found something related but not sure if it helps: https://stackoverflow.com/questions/41950021/typeerror-not-supported-between-instances-of-str-and-int

I changed title to be more specific and attached new log with a less noise. Maybe you could find something there.

**Comment by yarda** [comment]
Maybe I found the root cause, please test.

**Comment by Maryse47** [comment]
It looks that nailed it. Thx for help.
