### ISSUE TITLE
tuned conf files should be put in /etc/tuned

### ISSUE THREAD

**Issue by renich** [redhat-performance/tuned#162]
I think the tuned configuration files should go in `/etc/tuned`; at least the overrides for them. If I edit any of them, I have to take care of stuff. I might be missing something and maybe this is a non-issue. 

Just to illustrate my dilemma:

I would like to declare my drive here: 

```
# /usr/lib/tuned/balanced/tuned.conf 
#
# tuned configuration
#

[main]
summary=General non-specialized tuned profile

[cpu]
governor=conservative
energy_perf_bias=normal

[audio]
timeout=10

[video]
radeon_powersave=dpm-balanced, auto

[disk]
# Comma separated list of devices, all devices if commented out.
# devices=sda

[scsi_host]
alpm=medium_power
```

But, if I edit a file in `/usr/lib`; which I never do, then, next time I update, the conf file will be overwritten.

**Comment by yarda** [comment]
You have two options:
a) copy the profile from the /usr to the /etc and then customize it - the profile from the /etc will be preferred (in case of the same name), or
b) create new profile in the /etc (can even have the same name) and include the stock profile from the lib, e.g.
[main]
include=balanced
...
and then just override what you need

in case of a), you will freeze the stock profile. In case of b) you will be in sync with the stock profile changes (delivered by the Tuned RPMs updates).

**Comment by yarda** [comment]
Copy from the /usr/lib/tuned/... to /etc/tuned/...., or create new profile under /etc/tuned. This wasn't clear from my previous comment.

**Comment by olysonek** [comment]
I think there's nothing to be done here, closing. Feel free to reopen if I missed something.
