### ISSUE TITLE
[RFE] tuned recommend auto-parent

### ISSUE THREAD

**Issue by jeremyeder** [redhat-performance/tuned#17]
https://bugzilla.redhat.com/show_bug.cgi?id=1426654

In order to deliver optimal performance on both bare metal and virtual machines, we have a separate profile called virtual-guest which adds tunings we found beneficial for VMs.

This adds some complexity for layered products in that they must now maintain separate profiles for bare metal and VMs.

We would like to reduce this complexity and only have a single profile for layered products that automatically sets the correct parent based on the existing recommend feature.

**Comment by yarda** [comment]
This is an request to extend Tuned engine to:
- support variables and built-in functions in [main] block of tuned.conf
- add something like ${f:vm:STR1:STR2} function which would expand to STR1 in case of VM (i.e. virt-what returns non empty string) or STR2 in case of bare metal (virt-what returns empty string).

This could be used by e.g.:
[main]
include=${f:vm:virtual-guest:throughput-performance}

This would include 'virtual-guest' profile if running inside VM and 'throughput-performance' if running on bare metal.

This would also allow combinations like:
[main]
include=myprofile-${f:vm:guest:host}

would result in inclusion of myprofile-guest inside VM and myprofile-host on bare-metal.

**Comment by jmencak** [comment]
Tested https://github.com/redhat-performance/tuned/commit/a1b9e606449715202b4feccf8b6de23e278b776f 

with
[main]
include=virtual-${f:virt_check:guest:host}

and tuned-2.8.0-3

worked fine for me, thanks.

**Comment by yarda** [comment]
Thanks for testing, fixed by a1b9e606449715202b4feccf8b6de23e278b776f, closing.
