### ISSUE TITLE
tuned polkit rules must be more restrictive - ordinary X users must not be able to start/stop tuned

### ISSUE THREAD

**Issue by watologo1** [redhat-performance/tuned#180]
These should all be auth_admin by default, X users must not be able to disable/start/stop/reload the systemd tune daemon?

com.redhat.tuned.disable                        auth_admin:auth_admin:yes
com.redhat.tuned.reload                         auth_admin:auth_admin:yes
com.redhat.tuned.start                          auth_admin:auth_admin:yes
com.redhat.tuned.stop                           auth_admin:auth_admin:yes

Also security people at SUSE have problems with the newly introduced:
get_all_plugins and friends which ends up in load_all_plugins() and which is suggested to be executable/triggerable by all users yes:yes:yes.
Ideally this should be auth_admin as well.

**Comment by yarda** [comment]
All of them currently have:
```
      <allow_any>auth_admin</allow_any>
      <allow_inactive>auth_admin</allow_inactive>
      <allow_active>yes</allow_active>
```
Which IMHO allows only people logged directly into the machine on a TTY or X display (i.e. mostly people with physical access to the machine) without auth. It's same for many other policies. E.g. if the user is already allowed to reboot or power-off the machine, I think that changing the performance profile cannot cause more harm, e.g. on Fedora:
```
$ pkaction -v --action-id org.freedesktop.login1.reboot
org.freedesktop.login1.reboot:
  description:       Reboot the system
  message:           Authentication is required for rebooting the system.
  vendor:            The systemd Project
  vendor_url:        http://www.freedesktop.org/wiki/Software/systemd
  icon:              
  implicit any:      auth_admin_keep
  implicit inactive: auth_admin_keep
  implicit active:   yes
  annotation:        org.freedesktop.policykit.imply -> org.freedesktop.login1.set-wall-message

$ pkaction -v --action-id org.freedesktop.login1.power-off
org.freedesktop.login1.power-off:
  description:       Power off the system
  message:           Authentication is required for powering off the system.
  vendor:            The systemd Project
  vendor_url:        http://www.freedesktop.org/wiki/Software/systemd
  icon:              
  implicit any:      auth_admin_keep
  implicit inactive: auth_admin_keep
  implicit active:   yes
  annotation:        org.freedesktop.policykit.imply -> org.freedesktop.login1.set-wall-message
```
Just my two cents - I am open to discussion.

What's the problem with the get_all_plugins and friends? It should just show what's available/installed and it cannot modify anything. From my point of view it's similar to listing of all Tuned available profiles.

**Comment by mgerstner** [comment]
> What's the problem with the get_all_plugins and friends? It should just show what's available/installed 
> and it shouldn't modify anything. From my point of view it's similar to listing of all available Tuned profiles.

Well this came from me, actually. My reasoning is as follows (quote from my review report):

These new actions here allow any user (upstream suggests setting yes:yes:yes
for all these new actions) to enumerate available plugins that tuned knows
about. While this sounds like a read-only operation, the daemon actually loads
*all* plugins in the process and thus executes plugin code in the root
context.
  
By whitelisting these actions we're actually giving out a carte blanche for
any current or future plugins that might be shipped for tuned to behave nicely
in this context.

**Comment by yarda** [comment]
I agree it could currently ease attack vector (we would like to improve it in the future not to execute any code), but it requires the attacker to have the root write permissions to install the malicious plugin. And if she/he already has write permissions to plugins location, she/he can already change the active plugin to do the malicious action. But I am open to discussion.

**Comment by mgerstner** [comment]
Are these new D-Bus called user anywhere at all at the moment? I would like to downgrade them to "auth_admin:auth_admin:yes" at least.

It's of course true that nobody can install arbitrary plugins without root access. But if a badly written plugin is installed by the administrator (or via package managers that allow this to regular users) then it could easily open up a security issue.

**Comment by yarda** [comment]
> Are these new D-Bus called user anywhere at all at the moment? I would like to downgrade them to "auth_admin:auth_admin:yes" at least.
> 
I think it's currently used just by the tuned-gui, so the current policy is unimportant.

Fair enough, I am not against.

**Comment by watologo1** [comment]
Whatabout start/stop/reload/disable systemd tuned.service rights?

This should be allowed to root user only. Switching profiles at runtime may make sense, but whether tuned should be started and available on a system is a thing which system administrator should decide at installation time?

**Comment by olysonek** [comment]
I don't really have a strong opinion on all this, so just my 2 cents: if we're restricting the use of `get_all_plugins`, then we might as well restrict switching the profile. Because if some plugin is installed, then it's likely that some profile that uses that plugin is also installed. So by allowing the user to switch profiles, we're potentially allowing them to execute code from any plugin (an much more code than in `get_all_plugins`).

**Comment by watologo1** [comment]
It is about setting get_all_plugins to:
auth_admin:auth_admin:yes
instead of (as currently suggested):
yes:yes:yes
the same as the right to switch profiles.

Looks like we have more or less the same opinion?

I make up 2 patches, one for the get_all_plugins (and friends) and one for the systemd service manipulation.

**Comment by olysonek** [comment]
Oh, right. I misread what was being proposed. Sorry!

**Comment by olysonek** [comment]
> These should all be auth_admin by default, X users must not be able to disable/start/stop/reload the systemd tune daemon?
> 
> com.redhat.tuned.disable auth_admin:auth_admin:yes
> com.redhat.tuned.reload auth_admin:auth_admin:yes
> com.redhat.tuned.start auth_admin:auth_admin:yes
> com.redhat.tuned.stop auth_admin:auth_admin:yes

...

> Whatabout start/stop/reload/disable systemd tuned.service rights?
> 
> This should be allowed to root user only. Switching profiles at runtime may make sense, but whether tuned should be started and available on a system is a thing which system administrator should decide at installation time?

There seems to be some confusion about what these DBus calls actually do (admittedly, they do have rather confusing names). They don't manipulate `tuned.service`. And to be able to call them in the first place, the tuned daemon needs to be already running. Here's what they do:
* `disable` unapplies any currently applied profile and clears the "preset" profile
* `reload` unapplies the currently applied profile and applies a new profile according to `/etc/tuned/active_profile`, `/etc/tuned/profile_mode` and `recommend.conf` files
* `start` applies the preset profile
* `stop` unapplies any currently applied profile

So all of these amount to switching the currently applied profile. `tuned.service` remains running after any of these are called. The service is not manipulated in any way.

**Comment by olysonek** [comment]
Heh, I see that the description of the calls in the policy file only adds to the confusion... Patches for that are welcome.

**Comment by mgerstner** [comment]
> Heh, I see that the description of the calls in the policy file only adds to the confusion... Patches for that are welcome.

I think merging the start and stop actions into something like a "pause" or "toggle" action might be more clear. Or "start_profile" and "stop_profile" or something like that.

**Comment by watologo1** [comment]
I had a quick look:
start/stop/reload/disable cleanup may make things worse. This exists for quite a while.
Especially polkit is an interface which is evil to rename.
And this is what the polkit security settings are for in the end.
auth_admin is what I would set, at least it's not yes:yes:yes.
Thanks for the quick merge of the latest plugin polkit change/patch related to this one.
I close this one.
