### ISSUE TITLE
tuned-adm  profile cpu-partitioning "Requested profile 'cpu-partitioning' doesn't exist"

### ISSUE THREAD

**Issue by alags19** [redhat-performance/tuned#191]
I am not able to activate the cpu-partitioning profile. I am running RHEL 7.4.

**#### tuned-adm  profile cpu-partitioning_
Requested profile 'cpu-partitioning' doesn't exist.**

Yum Install fails too with locating the right tuned packages for CPU-Paritioning profile.

**###** yum install -y tuned-profiles-cpu-partitioning.noarch
**Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Resolving Dependencies
--> Running transaction check
---> Package tuned-profiles-cpu-partitioning.noarch 0:2.7.1-5.el7fdp will be installed
--> Processing Dependency: tuned = 2.7.1 for package: tuned-profiles-cpu-partitioning-2.7.1-5.el7fdp.noarch
--> Processing Dependency: tuna for package: tuned-profiles-cpu-partitioning-2.7.1-5.el7fdp.noarch
--> Finished Dependency Resolution
Error: Package: tuned-profiles-cpu-partitioning-2.7.1-5.el7fdp.noarch (osp10)
           Requires: tuned = 2.7.1
           Installed: tuned-2.8.0-5.el7.noarch (@anaconda/7.4)
               tuned = 2.8.0-5.el7
Error: Package: tuned-profiles-cpu-partitioning-2.7.1-5.el7fdp.noarch (osp10)
           Requires: tuna
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest_**

**Comment by olysonek** [comment]
The missing dependencies are provided in a separate repository - NFV, I think. Please contact Red Hat support for information on how to enable that repository.

**Comment by yarda** [comment]
It seems you have newer Tuned (2.8.0) from the RHEL-7.4 repo and older cpu-partitioning profile (2.7.1-5) from the FDP repo. The versions of the engine and the profile have to match. The tuned-profies-cpu-partitioning package should be available together with the Tuned package from the product repository (client/server/workstation). You should either downgrade the Tuned package to the version from the FDP. Or update both to the version from the RHEL repo. In case of problem please contact Red Hat support (https://www.redhat.com/support).
