### ISSUE TITLE
Add support for autoneg and ring size in ethtool module

### ISSUE THREAD

**Issue by redrac** [redhat-performance/tuned#2]
It would be nice to set other ethtool settings besides -C and -K; specifically -G (ring buffer size) and -A (autoneg settings).

**Comment by jeremyeder** [comment]
Agreed.  Can you think of any others besides -G and -A?

There's a little potential gotcha with -G in that some NICs don't support adjusting it, and those that do, the value of the ring buffer differs, so you really do have to know what you're doing.  In other words, they don't make sense in profiles that Red Hat ships. I'll assume you were just wanting to use it in your own profile?

If you don't mind me asking, what is the use-case please?  Are you trying to handle rx UDP floods?

**Comment by redrac** [comment]
Those were the only two that came to mind -- I think that coalesce and ring buffer are probably the most used. If you mean malicious floods, no; my use cases are situations where we have very high throughput servers (some on 1G connected to 10G switches or 10G to 10G) where increasing the ring buffer will help us prevent drops when we are unable to process the packets quick enough. These hosts are hosting a code repo that gets hit by a number of hosts at the same time or they are hosts generating traffic to a large number of clients and getting a bunch of data back from the clients. Usually, these are brief bursts where we are saturating the NIC. Also, just generally I like to have the ring buffers maxed out -- not much downside.
