### ISSUE TITLE
el8 python3 defirqaffinity.py

### ISSUE THREAD

**Issue by bcg62** [redhat-performance/tuned#201]
```
$  sudo /usr/libexec/platform-python /usr/libexec/tuned/defirqaffinity.py remove 0,28,29,30,31
Traceback (most recent call last):
  File "/usr/libexec/tuned/defirqaffinity.py", line 111, in <module>
    fo.write(string)
TypeError: a bytes-like object is required, not 'str'
```

https://stackoverflow.com/questions/33054527/typeerror-a-bytes-like-object-is-required-not-str-when-writing-to-a-file-in

seems like the following needs to be changed 

`fo.write(string)` to `fo.write(string.encode())`

**Comment by yarda** [comment]
Thanks for the report. It's caused by switch to python3. I don't think we need to open the files in binary mode, so just removing the 'b' in the 'open' should be enough.
