### ISSUE TITLE
RFE: a way to return instance option to default

### ISSUE THREAD

**Issue by yarda** [redhat-performance/tuned#227]
For example `profile1`:
```
[cpu]
force_latency=10
no_turbo=1

[disk]
readahead=4098
```
I `profile2` I want to include `profile1` and drop just the `force_latency`. Currently I have to write:
```
[main]
include=profile1

[cpu]
replace=true
no_turbo=1
```
I.e. there is no way to just drop one option and return it to its defaults (i.e. usually None).

**Comment by yarda** [comment]
I thought about multiple ways how to extend the syntax to support this:
a) `force_latency=`
This may not work for options where user needs to set empty string ""
b) special operator on the left side, e.g. `:`, e.g. `force_latency:=`
When using it on the left side we probably do not need to implement escaping, but it will require some 'hackish' implementation.
c) special operator on the first position of the option, e.g. `:`, e.g. `:force_latency=`
This is quite unclear syntax, and we will also need additional `=` because our parser requires it.
d) special operator on the right side, e.g. `:`, e.g. `force_latency=:`
This will require escaping, because there may be options where user wants just literal `:`
e) special option which will list what to drop, e.g. `drop=option1[,option2[,..]]`
I.e.:
```
[cpu]
drop=force_latency
```
And the `drop` will be not inhereted, just utilized in the profile merger.

Any other opinions?

**Comment by olysonek** [comment]
@yarda I think I like best the `drop` option approach.
