### ISSUE TITLE
Tuned profile not yet applied when daemon is registered as started

### ISSUE THREAD

**Issue by xytis** [redhat-performance/tuned#23]
Currently tuned uses ```Type=dbus```, which registers tuned service as it binds to dbus.
Services that require particular system parameters at startup (namely redis) even with systemd dependency ```After=tuned.service``` start with undefined parameters.

I would suggest implementing dbus notification once a configured profile is loaded and switch to ```Type=notify``` in systemd startup script.

**Comment by yarda** [comment]
It makes sense.
