### ISSUE TITLE
Failed to open memory buffer (/dev/mem): Operation not permitted

### ISSUE THREAD

**Issue by RMPR** [redhat-performance/tuned#232]
When I tried to enable the balanced profile with:
```
sudo tuned-adm profile balanced
```
I got the following error message:
```
** COLLECTED WARNINGS **
Failed to open memory buffer (/dev/mem): Operation not permitted
No SMBIOS nor DMI entry point found, sorry.
** END OF WARNINGS **
```
While
`sudo dmidecode` displays correctly the information needed.
After research, I found out that the problem can be with python3-dmidecode because the following code: 
```
import dmidecode
print(dmidecode.bios())
```
prints an empty dictionary. 
It's an issue I want to tackle, can you provide me some guidance ? I've already read the CONTRIBUTING.md I want to know if I need to work on the tuned part (by parsing the output of the dmidecode command directly for example) or on the python-dmidecode part ?

**Comment by yarda** [comment]
Which distro? And which Tuned version?

**Comment by olysonek** [comment]
And which architecture? :)

**Comment by RMPR** [comment]
Fedora workstation 30, kernel 5.3.14-200, tuned 2.12.0

Dec 9, 2019 10:43:40 AM Jaroslav Škarvada <notifications@github.com>:

**Comment by yarda** [comment]
This seems strange, in the tuned/utils/profile_recommender.py there is the following code:
```
have_dmidecode = False
try:
	if (os.geteuid() == 0 and platform.machine() in ["i386", "i486", "i586", "i686", "x86_64"]):
		import dmidecode
		have_dmidecode = True
except:
	pass
```
Which should handle it. So it seems either your euid is not 0 or the code doesn't match your architecture.

**Comment by yarda** [comment]
So if `sudo dmidecode` works, `sudo tuned-adm` should also work.

**Comment by yarda** [comment]
Also I am unable to reproduce:
```
$ sudo tuned-adm profile balanced
$ sudo dmidecode
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 2.7 present.
60 structures occupying 2411 bytes.
...
$ rpm -q tuned
tuned-2.12.0-1.fc30.noarch
$ uname -p
x86_64
```

**Comment by yarda** [comment]
I have older kernel 5.3.13-200.fc30.x86_64, but I think it shouldn't be the source of the problem, I will retry later with 5.3.14.

**Comment by RMPR** [comment]
One thing I should note is I installed TLP then removed it before trying to use tuned

**Comment by RMPR** [comment]
And I configured a laptop profile following the instructions in [this](https://www.reddit.com/r/Fedora/comments/5pueys/how_to_save_power_with_your_laptop_running_fedora/) reddit post that's when I first encountered the issue.

**Comment by yarda** [comment]
I think both (TLP and the instructions) shouldn't cause the problem.

If you run the code you previously pasted:
```
import dmidecode
print(dmidecode.bios())
```
with sudo, do you see the error? Does the code work?

**Comment by RMPR** [comment]
```
sudo python3
Python 3.7.5 (default, Oct 17 2019, 12:09:47)
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dmidecode
>>> print(dmidecode.bios())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: [src/dmidecodemodule.c:328] Error decoding DMI data
```

**Comment by RMPR** [comment]
And after closing the interpreter with <kbd>Ctrl+d</kbd> I get the previous error message
```
** COLLECTED WARNINGS **
Failed to open memory buffer (/dev/mem): Operation not permitted
No SMBIOS nor DMI entry point found, sorry.
Failed to open memory buffer (/dev/mem): Operation not permitted
** END OF WARNINGS **
```

**Comment by yarda** [comment]
Could you try running the following code with sudo:
```
import os
import platform
print(os.geteuid())
print(platform.machine())
```
And post STDOUT results, also please try running the following:
```
sudo id
````
And also post result of:
```
ls -l /dev/mem
```

**Comment by RMPR** [comment]
```
>>> import os
>>> import platform
>>> print(os.geteuid())
0
>>> print(platform.machine())
x86_64
```
```
sudo id
uid=0(root) gid=0(root) groups=0(root) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```
```
sudo ls -l /dev/mem
crw-r-----. 1 root kmem 1, 1 Dec  9 10:18 /dev/mem
```

**Comment by yarda** [comment]
@RMPR thanks, also please try the following with su:
```
su -
dmidecode
```
And also still in the su shell try running the python reproducer:
```
import dmidecode
print(dmidecode.bios())
```

**Comment by RMPR** [comment]
Unfortunately I disabled root login but I think the same will apply.

**Comment by yarda** [comment]
Your permissions looks good. So maybe the error you are receiving from dmidecode library is just misleading and doesn't mean that it cannot open the /dev/mem, but that it cannot parse it. This is probably bug in the dmidecode library. I am afraid the only thing we could do in Tuned is to add configuration option for disabling dmidecode.

**Comment by yarda** [comment]
@RMPR could you open bug against python-dmidecode library with the simple reproducer we used? It has probably some trouble with your DMI table.

**Comment by RMPR** [comment]
I saw here [Bug 1435430 - yum warning: /dev/mem (mmap): Operation not permitted ](https://bugzilla.redhat.com/show_bug.cgi?id=1435430) that "this is expected behavior. The kernel doesn't allow access to /dev/mem for any architecture other than x86 for security reasons."

**Comment by yarda** [comment]
> I saw here [Bug 1435430 - yum warning: /dev/mem (mmap): Operation not permitted ](https://bugzilla.redhat.com/show_bug.cgi?id=1435430) that "this is expected behavior. The kernel doesn't allow access to /dev/mem for any architecture other than x86 for security reasons."

This is correct, but the bug is for ppc64le and you are on x86_64 where it should work (and it works for me).

**Comment by RMPR** [comment]
The repository doesn't seem to be active, can I implement the flag mentioned earlier ?

**Comment by yarda** [comment]
> The repository doesn't seem to be active, I don't know if I can implement a flag to toggle that behaviour.

Please open downstream Fedora bugzilla against python-dmidecode package. I think they will need dumps of your DMI table to fix the parser. I guess it's parser problem as you wrote earlier that the dmidecode tool itself works for you (it uses different parser implementation).

Regarding the Tuned configuration option pull requests are welcome. I meant global config option (in file /etc/tuned/tuned-main.conf) as a workaround for people who would experience the same problem. I meant something like 'dmidecode=0' for global disablement of dmidecode support.

**Comment by outSH** [comment]
/dev/mem access is restricted (even for root) when secure boot kernel lockdown is enabled, /sys/firmware/dmi/* should be used to get smbios instead (it's primary source for dmidecode tool now). Since python-dmidecode isn't maintained anymore, I think it would be reasonable to use dmidecode output instead (I don't know any other reliable alternative).

**Comment by olysonek** [comment]
Yes, I think we should go back to using the `dmidecode` tool. Patches are welcome. The patch should be written in such a way that the tool is executed only once during the entire Tuned runtime, i.e. the output should be cached. This is because we're trying to limit the use of external executables for performance reasons.
