### ISSUE TITLE
Looking for description of realtime profile

### ISSUE THREAD

**Issue by DavidA2014** [redhat-performance/tuned#238]
The Red Hat tuning guide provides a description of many profiles [here](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/performance_tuning_guide/chap-red_hat_enterprise_linux-performance_tuning_guide-tuned) but I haven't found a description of the default characteristics of the **realtime** profile.  What are those characteristics?

Can you suggest why average performance might drop when switching from **balanced** to **realtime**?  Could it be to do with the power saving settings?

**Comment by yarda** [comment]
> The Red Hat tuning guide provides a description of many profiles [here](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/performance_tuning_guide/chap-red_hat_enterprise_linux-performance_tuning_guide-tuned) but I haven't found a description of the default characteristics of the **realtime** profile. What are those characteristics?
> 
We need to improve the documentation.

Currently tuned-2.13.0:
The realtime profiles is based on network-latency which is based on latency-performance:
realtime <- network-latency <- latency-performance

Content of profiles as in tuned-2.13.0:
https://github.com/redhat-performance/tuned/blob/193b9fa6412bf915c1a4a0dfd5e38edd224ad549/profiles/realtime/tuned.conf
https://github.com/redhat-performance/tuned/blob/193b9fa6412bf915c1a4a0dfd5e38edd224ad549/profiles/realtime/script.sh
https://github.com/redhat-performance/tuned/blob/193b9fa6412bf915c1a4a0dfd5e38edd224ad549/profiles/network-latency/tuned.conf
https://github.com/redhat-performance/tuned/blob/193b9fa6412bf915c1a4a0dfd5e38edd224ad549/profiles/latency-performance/tuned.conf

> Can you suggest why average performance might drop when switching from **balanced** to **realtime**? Could it be to do with the power saving settings?
>
Which OS, kernel, Tuned version?

Could you try tuned-2.13.0? There were tweaks for better performance.

**Comment by DavidA2014** [comment]
@yarda Thanks for your reply.

    Which OS, kernel, Tuned version? Could you try tuned-2.13.0?

I'm using:
- CentOS Linux release 7.4.1708 (Core)
- 3.10.0-957.27.2.el7.x86_64

I'm sorry, I don't know how to check _Tuned_ version nor how to update to tuned-2.13.0.

Actually, we're not running a realtime kernel so I guess we shouldn't be using _realtime_.  I now think that _throughput-performance_ would be a better choice for us.

We do want to isolate cpus so that no other processes or interrupts are running on a certain core, leaving it free for our high performance process. Can we set _isolcpus_ when using _throughput-performance_, or is there a better way of achieving this?

**Comment by yarda** [comment]
> I'm using:
> 
>     * CentOS Linux release 7.4.1708 (Core)
> 
>     * 3.10.0-957.27.2.el7.x86_64
> 
> 
> I'm sorry, I don't know how to check _Tuned_ version nor how to update to tuned-2.13.0.
> 
In this case I do not recommend upgrading to tuned-2.13.0 - it's for newer kernels (RHEL-8, Fedora, etc.)

> Actually, we're not running a realtime kernel so I guess we shouldn't be using _realtime_. I now think that _throughput-performance_ would be a better choice for us.
> 
It's likely. Realtime profiles are optimized for realtime kernels.

> We do want to isolate cpus so that no other processes or interrupts are running on a certain core, leaving it free for our high performance process. Can we set _isolcpus_ when using _throughput-performance_, or is there a better way of achieving this?

Try cpu-partitioning Tuned profile:
```
# yum install tuned-profiles-cpu-partitioning
```
Then set CPUs you want to isolate in the `/etc/tuned/cpu-partitioning-variables.conf`, e.g.:
```
isolated_cores=2,4-7
```
For isolating cores 2,4,5,6,7 and finally activate the profile:
```
# tuned-adm profile cpu-partitioning
```

**Comment by DavidA2014** [comment]
@yarda Thanks again. Would you expect _cpu-partitioning_ to have similar performance to _throughput-performance_?

**Comment by yarda** [comment]
> @yarda Thanks again. Would you expect _cpu-partitioning_ to have similar performance to _throughput-performance_?

The cpu-partitioning profile is based on network-latency profile which is based on latency-performance profile. I think the performance can be even better than throughput-performance in cost of the higher power consumption - e.g. the latency-performance profile is locking the CPU to C-state 1. But the best is to benchmark it yourself on your platform. If you want to customize the throughput-performance profile to support isolcpus, you can create your own Tuned profile for it:

```
# mkdir -p /etc/tuned/my-profile
# cat >  /etc/tuned/my-profile/tuned.conf << :EOF
[main]
include=throughput-performance

[bootloader]
cmdline=isolcpus=1,3
:EOF
# tuned-adm profile my-profile
# reboot
```
This will apply the throughput-performance Tuned profile and also add `isolcpus=1,3` to isolate the cores 1 and 3.

**Comment by DavidA2014** [comment]
@yarda Thanks again.

**Comment by yarda** [comment]
Just a side note, the cpu-partitioning Tuned profile is not using the isolcpus for cores isolation, it's using systemd's cores affinity, nohz_full and other tweaks.

**Comment by DavidA2014** [comment]
@yarda Will those tweaks shield the specified core from hosting interrupt routines?

**Comment by yarda** [comment]
> @yarda Will those tweaks shield the specified core from hosting interrupt routines?

Yes.

If you need to create custom profile, feel free to take inspiration from the "system profiles" which are hosted under the `/usr/lib/tuned` directory.

**Comment by DavidA2014** [comment]
Thanks
