### ISSUE TITLE
Execute multiple scripts in one profile

### ISSUE THREAD

**Issue by gsauthof** [redhat-performance/tuned#257]
Looking at

https://github.com/redhat-performance/tuned/blob/15a34ee68d2c3e1c185305c8a03847f58535a7fa/tuned/plugins/plugin_script.py#L35

it seems like it would be possible to call multiple scripts from one tuned profile.

But how to do that exactly?

I've tried some syntactic variations - without success.

For example,

```
[script]
script = ${i:PROFILE_DIR}/one.sh
script = ${i:PROFILE_DIR}/two.sh   # error!
```
does **not** work.

**Comment by olysonek** [comment]
This should work:
```
[script_1]
type=script
script = ${i:PROFILE_DIR}/one.sh

[script_2]
type=script
script = ${i:PROFILE_DIR}/two.sh
```

**Comment by gsauthof** [comment]
Yes, this works fine. Thank you for the hint.
