### ISSUE TITLE
Tuned won't start on Centos 7

### ISSUE THREAD

**Issue by xx7879** [redhat-performance/tuned#267]
Installed normal.
`$ systemctl start tuned`
Job for tuned.service failed because the control process exited with error code. See "systemctl status tuned.service" and "journalctl -xe" for details.

`$systemctl status tuned.service`
tuned.service - Dynamic System Tuning Daemon
   Loaded: loaded (/usr/lib/systemd/system/tuned.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-05-19 19:28:37 UTC; 28s ago
     Docs: man:tuned(8)
           man:tuned.conf(5)
           man:tuned-adm(8)
  Process: 10265 ExecStart=/usr/sbin/tuned -l -P (code=exited, status=1/FAILURE)
 Main PID: 10265 (code=exited, status=1/FAILURE)

May 19 19:28:37 any2.domain.com tuned[10265]: reraise(exc_value, traceback)
May 19 19:28:37 any2.domain.com tuned[10265]: File "/usr/lib/python2.7/site-packages/pyudev/monitor.py", line 275, in set_receive_buffer_size
May 19 19:28:37 any2.domain.com tuned[10265]: self._libudev.udev_monitor_set_receive_buffer_size(self, size)
May 19 19:28:37 any2.domain.com tuned[10265]: File "/usr/lib/python2.7/site-packages/pyudev/_libudev.py", line 219, in check_errno
May 19 19:28:37 any2.domain.com tuned[10265]: raise exception_from_errno(errno)
May 19 19:28:37 any2.domain.com tuned[10265]: EnvironmentError: [Errno 1] Operation not permitted: None
May 19 19:28:37 any2.domain.com systemd[1]: tuned.service: main process exited, code=exited, status=1/FAILURE
May 19 19:28:37 any2.domain.com systemd[1]: Failed to start Dynamic System Tuning Daemon.
May 19 19:28:37 any2.domain.com systemd[1]: Unit tuned.service entered failed state.
May 19 19:28:37 any2.domain.com systemd[1]: tuned.service failed.

Please help, thank.

**Comment by yarda** [comment]
I am not sure why the size of receive buffer of the udev cannot be set on centos - I will have to provision centos to try, but we can add exception handler for this problem not to crash Tuned.

**Comment by yarda** [comment]
I was unable to reproduce the problem on cleanly provisioned centos7 (CentOS Linux release 7.6.1810 (Core)):
```
# systemctl start tuned
# systemctl status tuned
● tuned.service - Dynamic System Tuning Daemon
   Loaded: loaded (/usr/lib/systemd/system/tuned.service; enabled; vendor preset: enabled)
   Active: active (running) since Út 2020-05-19 15:43:48 EDT; 4s ago
     Docs: man:tuned(8)
           man:tuned.conf(5)
           man:tuned-adm(8)
 Main PID: 12309 (tuned)
   CGroup: /system.slice/tuned.service
           └─12309 /usr/bin/python2 -Es /usr/sbin/tuned -l -P
```

From the libudev manual page:
```
The CAP_NET_ADMIN capability must be contained in the effective capability set of the caller for this method to succeed. Otherwise EnvironmentError will be raised, with errno set to EPERM. Unprivileged processes typically lack this capability.
```
Is Tuned running on your system privileged with the CAP_NET_ADMIN?

We should add check for it and don't try to tweak the udev receive buffer if Tuned lacks the CAP_NET_ADMIN capability.

**Comment by xx7879** [comment]
This is not "pure" centos 7. I downgraded PHP 7.4 to 7.3. And upgraded Maridb to 10.3. Tuned Mysql with mysqltuner.pl.

I tried:
$ `setcap cap_net_admin+ep /usr/sbin/tuned`

$ `getcap /usr/sbin/tuned`
/usr/sbin/tuned = cap_net_admin+ep

$ `capsh --print`
Current: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,35,36+ep
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,35,36
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
uid=0(root)
gid=0(root)
groups=0(root)


Am I correct with that? 
But the same error info is still there when starting tuned after reboot.
Thanks for your time.

**Comment by olysonek** [comment]
The way I understand capabilities is that you get CAP_NET_ADMIN automatically when you're running as root.

The only time I've seen this error is when someone ran Tuned in a container. Is this a CentOS container?

**Comment by xx7879** [comment]
No, not a container.

**Comment by yarda** [comment]
[tuned-debug-pcaps.zip](https://github.com/redhat-performance/tuned/files/4664524/tuned-debug-pcaps.zip)

Could you try to debug with the attached patch? I.e.:
```
# dnf install libcap zip patch
# unzip tuned-debug-pcaps.zip
# patch -p0 -d/ < tuned-debug-pcaps.patch
```
Restart Tuned and then you could see in the log (/var/log/tuned/tuned.log) Tuned capabilities like:
```
2020-05-21 16:12:58,586 ERROR    tuned.hardware.inventory: * getpcaps pid=17380: Capabilities for `17380': =
cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,
cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,
cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,
cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,
cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,
cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,
cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,
cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,
cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read+ep
```
The "ERROR" string there is OK, it's just to get attention :)

You can remove the patch just by reinstalling Tuned:
```
# dnf reinstall tuned
```

**Comment by yarda** [comment]
If you could get the Tuned running you could also get the effective caps just by running:
```
# getpcaps `cat /run/tuned/tuned.pid`
```
But the patch is better, because it shows the caps just before the failing libudev API is called and Tuned crashes.

**Comment by yarda** [comment]
After investigation of the problem I found out that the source of the problem is that Tuned is running inside the openvz/lxc container. It has the CAP_NET_ADMIN capability, but the udev functionality in the container is limited. The udev_monitor doesn't return any events - this is expectable and known, but undocumented in the libudev/systemd manual pages. I will open bugzilla requesting update of the libudev devel documenatation.

Unfortunately, Tuned needs patching otherwise it will crash in the container. I will PR patches for it. It's quite surprising that nobody has reported this problem so far. The question is whether Tuned in container makes any sense - there is not much you can tune in the container - sysctl/sysfs mostly doesn't work and it's not possible to tune the bare metal from the container. I.e. there is probably no need to fix this problem in RHEL-7, but I will probably initiate KB article about it. With the stock virtual-guest profile (i.e. if the user doesn't have custom Tuned profiles) I think it's OK to disable Tuned in the container by:
```
# systemctl stop tuned
# systemctl disable tuned
```

**Comment by richm** [comment]
I noticed something similar developing the kernel_settings role.  I had to do this for container testing: https://github.com/linux-system-roles/kernel_settings/blob/master/library/kernel_settings.py#L533-L537
```
    # this call fails on ubuntu and containers, so mock it for testing
    import pyudev.monitor

    orig_set_receive_buffer_size = pyudev.monitor.Monitor.set_receive_buffer_size
    pyudev.monitor.Monitor.set_receive_buffer_size = lambda self, size: None
```

**Comment by yarda** [comment]
Regarding the libudev documentation I opened: https://bugzilla.redhat.com/show_bug.cgi?id=1839210

**Comment by olysonek** [comment]
> The question is whether Tuned in container makes any sense

@yarda I thought that the Node Tuning Operator for OCP runs inside a container :). But I'm guessing that's a privileged container. Not sure if the udev operation works in that environment, though.

**Comment by xx7879** [comment]
I didn't realize OpenVZ is a container-based virtualization. Sorry for that.
Does that mean Tuned will not work on openvz VPS, and will on on KVM VPS?

**Comment by yarda** [comment]
It depends what you need to tune. If you use the default virtual-guest profile in the unprivileged container there is not much to tune, so I think in such case it's OK to disable Tuned. It can make sense for e.g. cpu-partitioning profile or some custom tuning (with custom Tuned profile). Nevertheless, there was a bug in Tuned - it shouldn't crash, thanks for the report. I created PR with the fix.

OpenVZ uses a shared kernel with a layer of virtualization. The kernel is shared by all VPS users on the node, thus the kernel is not customizable, so e.g. the sysctl tuning don't work there. The KVM shouldn't pose such limitation, because it's full HW virtualization - you run your own kernel in the guest and the kernel needn't be Linux, it can be anything you want, e.g. Windows.
