### ISSUE TITLE
Fedora bootloader cmdline does not add leading space

### ISSUE THREAD

**Issue by richm** [redhat-performance/tuned#268]
This looks a problem with tuned on Fedora 31 - does not appear to affect EL - not sure if other versions of Fedora are affected.  The problem can be easily reproduced on virtual machines which are based on the Fedora Cloud image e.g. http://mirrors.kernel.org/fedora/releases/31/Cloud/x86_64/images/Fedora-Cloud-Base-31-1.9.x86_64.qcow2 - have reproduced on local qemu/kvm and on OpenStack machines.  The problem does not affect bare metal, or virtual machines not based on the cloud images.

The tuned arguments added to `/proc/cmdline` do not have a leading space - so if I have `/etc/tuned/bootcmdline` with

`TUNED_BOOT_CMDLINE="spectre_v2=off nopti"`

`/proc/cmdline` looks like this:
```
BOOT_IMAGE=(hd0,msdos1)/boot/vmlinuz-5.6.13-200.fc31.x86_64 root=UUID=b1438b9b-2cab-4065-a99a-08a96687f73c
ro no_timer_check net.ifnames=0 console=tty1 console=ttyS0,115200n8spectre_v2=off nopti
```
You can "fix" the cmdline by using grubby to add another cmdline option:

`grubby --update-kernel=ALL --args=quiet`

after reboot, you will see something like this:

`cat /proc/cmdline`
```
BOOT_IMAGE=(hd0,msdos1)/boot/vmlinuz-5.6.13-200.fc31.x86_64 root=UUID=b1438b9b-2cab-4065-a99a-08a96687f73c
ro no_timer_check net.ifnames=0 console=tty1 console=ttyS0,115200n8 spectre_v2=off nopti quiet
```

**Comment by yarda** [comment]
I tried to reproduce this problem with 1minutetip. I think the problem is that buggy grub was used when the image was built. Try to upgrade it to at least grub2-common-2.02-106.fc31.noarch or newer, than reinstall it by:

# grub2-install /dev/vda

Replace /dev/vda with your root boot device and please report back.

**Comment by pcahyna** [comment]
Would it be possible to ask relengs to rebuild the images with correct grub version?

**Comment by richm** [comment]
> Would it be possible to ask relengs to rebuild the images with correct grub version?

I've asked Fedora how to do this.

**Comment by richm** [comment]
> I tried to reproduce this problem with 1minutetip. I think the problem is that buggy grub was used when the image was built. Try to upgrade grub to at least grub2-common-2.02-106.fc31.noarch or newer, than reinstall it by:
> 
> ```
> # grub2-install /dev/vda
> ```
> 
> Replace /dev/vda with your root boot device and please report back.

1) I'm still trying to programmatically determine if the system is using a bootloader with the buggy grub - I want the kernel_settings role to find out if setting bootloader cmdline will work - I don't know if I want the kernel_settings role to use `grub2-install` (or perhaps the tests)
2) It is not pretty to programmatically determine the boot device in Ansible

**Comment by yarda** [comment]
My opinion is that you are not responsible for bugs in other tools, so you probably don't need to workaround them. It seems this bug was present in Fedora 31 for short term and will be irrelevant once the Fedora 31 will get EOL which will happen in few months.

**Comment by yarda** [comment]
It seems there is nothing to do on the Tuned side - we utilize the grub BLS interface correctly and the grub bug was already fixed.

Switching to grubby will not bring us any benefit in the long term - grubby has its own problems and it would be one more dependency. AFAIK one of the reasons behind the BLS grub implementation was to drop grubby from the scriptlets.
