### ISSUE TITLE
Tuned broken by python3.9.1-1

### ISSUE THREAD

**Issue by Cheekchap** [redhat-performance/tuned#318]
Getting tuned.service error.....

 tuned[563785]:   File "/usr/lib/python3.9/site-packages/tuned/units/__init__.py", line 1, in <module>
 tuned[563785]:     from .manager import *
 tuned[563785]:   File "/usr/lib/python3.9/site-packages/tuned/units/manager.py", line 9, in <module>
 tuned[563785]:     from tuned.utils.global_config import GlobalConfig
 tuned[563785]:   File "/usr/lib/python3.9/site-packages/tuned/utils/global_config.py", line 3, in <module>
 tuned[563785]:     from validate import Validator
 tuned[563785]: ModuleNotFoundError: No module named 'validate'

Temporary fix until update.....

Edit

/usr/lib/python3.9/site-packages/tuned/utils/global_config.py

comment out line 3 code  `#from validate import Validator`

and add this line of code (as line 4)

`from configobj.validate import Validator`

Edit 

/usr/lib/python3.9/site-packages/tuned/gtk/gui_plugin_loader.py

comment out line 28 code  `#from validate import Validator`

and add this line of code (as line 29)
`
from configobj.validate import Validator`

**Comment by bobcom2** [comment]
Thank you! it finally works

**Comment by CZerta** [comment]
Hello. Can you provide more information about reproducibility? Like your distro, architecture and packages versions. I tried to reproduce the problem, bu with no success.

**Comment by bobcom2** [comment]
I was on manjaro minimum Linux version 5.9? You would just install it and it would break cause the kernel is a different python version

**Comment by CZerta** [comment]
According to https://forum.manjaro.org/t/tuned-2-15-0-1-broken-by-python-configobj-5-0-6-10/48154/9 there was issue with `python-configobj`. I tried it with new version of package and everything seems running fine. @yarda

**Comment by yarda** [comment]
@CZerta thanks for analysis. I.e. there is nothing to fix in TuneD upstream, closing this issue.
