### ISSUE TITLE
Incorrect data in profile_changed DBus event

### ISSUE THREAD

**Issue by xvitaly** [redhat-performance/tuned#326]
D-Bus event `profile_changed` raises two events on errors:
1. (correct): ('sadsdsadsdasda', false, "Requested profile 'sadsdsadsdasda' doesn't exist.")
2. (bogus): ('sadsdsadsdasda', true, 'OK.')

Steps to reproduce:
1. subscribe to `profile_changed` event or use any DBus debugger;
2. switch profile to non-existent (eg. `sadsdsadsdasda`);
3. two events will be raised: correct and bogus.

It should return only `Requested profile 'sadsdsadsdasda' doesn't exist.`.

**Comment by CZerta** [comment]
There should be two events, first is correct as you mentioned, the bogus one have wrong data, it should contain name of profile you had before the change. I hopefully sent a fix.

**Comment by xvitaly** [comment]
I think the second should be discarded completely.

**Comment by CZerta** [comment]
The second raises from the structure of method calling in daemon. Of course, can be changed, but I'll need confirmation for this from "higher places" ;-) @yarda

**Comment by yarda** [comment]
> I think the second should be discarded completely.

@xvitaly you meant the second D-Bus event? In such case check the log (I used non-existent 'xyz' profile):
```
2021-03-08 15:34:11,451 INFO     tuned.daemon.daemon: starting tuning
2021-03-08 15:34:11,456 INFO     tuned.daemon.daemon: static tuning from profile 'balanced' applied
dbus call switch_profile("xyz")
2021-03-08 15:35:25,372 INFO     tuned.daemon.daemon: stopping tuning
2021-03-08 15:35:25,374 ERROR    tuned.daemon.controller: Failed to apply profile 'xyz'
2021-03-08 15:35:25,374 INFO     tuned.daemon.controller: Applying previously applied profile.
2021-03-08 15:35:25,374 INFO     tuned.daemon.daemon: starting tuning
2021-03-08 15:35:25,380 INFO     tuned.daemon.daemon: static tuning from profile 'balanced' applied
```
I.e. it tries to load the 'xyz' profile, failed and reloaded the previous profile.

**Comment by xvitaly** [comment]
> @xvitaly you meant the second D-Bus event? In such case check the log (I used non-existent 'xyz' profile):

You shoud subscribe to `profile_changed` D-Bus signal.

**Comment by xvitaly** [comment]
@yarda Steps to reproduce:

1. Download our tuned-switcher: `git clone https://github.com/EasyCoding/tuned-switcher.git`
2. Switch to commit: `git checkout 7de85640a78269aa23ce51b76d8ef1ca9803171c`
3. Apply the following patch with removed profile existence checks:
```diff
diff --git a/src/tray/trayicon/trayicon.cpp b/src/tray/trayicon/trayicon.cpp
index 9423b67..42ee403 100644
--- a/src/tray/trayicon/trayicon.cpp
+++ b/src/tray/trayicon/trayicon.cpp
@@ -62,12 +62,7 @@ void TrayIcon::profileChangedEvent(const QString& profile, const bool result, co
 {
     if (result)
     {
-        QAction* profileAction = tunedProfiles[profile];
-        if (profileAction)
-        {
-            profileAction -> setChecked(true);
-            trayIcon -> showMessage(tr("Profile switched"), tr("The active profile was switched to %1.").arg(profile), QSystemTrayIcon::Information);
-        }
+        trayIcon -> showMessage(tr("Profile switched"), tr("The active profile was switched to %1.").arg(profile), QSystemTrayIcon::Information);
     }
     else
     {
```
4. Build and run applet.
5. Set profile: `tuned-adm profile xyz`
6. Two events will be fired (screenshot attached).

![image](https://user-images.githubusercontent.com/966711/110338197-06bc0f80-8027-11eb-919b-6aa76ccad336.png)

**Comment by xvitaly** [comment]
Raw results from D-Bus debugger:

```
('xyz', false, "Requested profile 'xyz' doesn't exist.")
('xyz', true, 'OK.')
```

Got 2 answers from D-Bus signal.

**Comment by yarda** [comment]
The current behaviour is to reload the previous profile on failure, i.e. that means two events (after the fix):
1. xyz failue
2. previous profile reloaded OK (e.g. balanced profile)

Because as the first step it unloads the previous profile, so you need to be notified when it is successfully reloaded.

**Comment by xvitaly** [comment]
> The current behaviour is to reload the previous profile on failure, i.e. that means two events (after the fix):

OK, got it. But currently it fires `xyz` - OK.

**Comment by CZerta** [comment]
> > The current behaviour is to reload the previous profile on failure, i.e. that means two events (after the fix):
> 
> OK, got it. But currently it fires `xyz` - OK.

Even from the linked PR?

**Comment by xvitaly** [comment]
> Even from the linked PR?

Didn't tested it. I use tuned from Fedora repositories.
