### ISSUE TITLE
correct spelling mistake

### ISSUE THREAD

**Issue by firexinghe** [redhat-performance/tuned#328]
Powertop submission：https://github.com/fenrus75/powertop/commit/30ea71aa63fcc02343559b15bc07cdff0840bf3b
run command：powertop2tuned new_profile_name --force
![image](https://user-images.githubusercontent.com/80017732/109905830-5bcfec80-7cda-11eb-98d1-4861d70c1004.png)

In the experiments/powertop2tuned.py file, in the class PowertopProfile function generateHTML
prefix = "PowerTOP outputing using base filename "

The "outputing" values of Powertop and Prefix are different.

**Comment by yarda** [comment]
Thanks, we will fix it.

**Comment by firexinghe** [comment]
Thanks
