### ISSUE TITLE
ConfigParser default delimiter causing errors

### ISSUE THREAD

**Issue by ajbucci** [redhat-performance/tuned#378]
In my powertop2tuned generated tuned.conf I have several devices with a colon in the path, for example:

> /sys/bus/pci/devices/0000:01:00.0

As far as I know ConfigParser does not allow the delimiters to be escaped, which causes this error:

> Cannot load profile(s) 'powersave': ("Cannot parse '/etc/tuned/powersave/tuned.conf'.", While reading from '/etc/tuned/powersave/tuned.conf' [line 42]: option '/sys/bus/pci/devices/0000' in section 'sysfs' already exists)

A simple fix for my particular issue would be to set the delimiter to only "=" whenever a ConfigParser is created. For example:

`config_parser = ConfigParser(delimiters=('='))`

**Comment by CZerta** [comment]
Hi. Sorry to hear. Can you provide snippet of some of this config? I probably understand where is the problem, but it'll probably need also "allow_no_value=True" param, because we don't use it on any place like it.

**Comment by Maryse47** [comment]
I created profile with `powertop2tuned` and hit the same thing (it's regression as some older tuned version worked fine with same conf). To reproduce you may add two simple lines in conf:
```
/sys/bus/pci/devices/0000:00:02.0/power/control=auto
/sys/bus/pci/devices/0000:04:00.0/power/control=auto
```

**Comment by jmencak** [comment]
Another side effect is that now it is no longer possible to write comments in this way:
```
key=value                 # comment
```
Reverting https://github.com/redhat-performance/tuned/pull/375 seems to resolve this issue for me.

**Comment by CZerta** [comment]
Hey. Did you tried if the linked PR resolved your issues?
