### ISSUE TITLE
Desktop file enhacements

### ISSUE THREAD

**Issue by gfa** [redhat-performance/tuned#45]
Hello

lintian, and desktop-file-validate, both complain about the desktop file, this patch solves the problem and installs tuned-gui.glade with 0644 permissions (exec permissions are not needed)

[desktop-file.patch.txt](https://github.com/redhat-performance/tuned/files/966587/desktop-file.patch.txt)

**Comment by yarda** [comment]
Thanks, I modified the patch to apply with the latest git head. Better is to use pull requests.

**Comment by yarda** [comment]
c139e6e01e9ec0a87a495e03e107bda7ab916f17
