### ISSUE TITLE
Run TuneD without D-Bus

### ISSUE THREAD

**Issue by maxpain** [redhat-performance/tuned#458]
Hi.

Can I use TuneD without D-Bus?
What will I lose if I run TuneD without it?

**Comment by yarda** [comment]
Hi,

yes, you can run without D-Bus.

- You will loose D-Bus API, e.g. the possibility to control and integrate TuneD with other tools e.g. Cockpit.
- The switching of the TuneD profiles will work with some sort of hack - the 'tuned-adm' command will fall-back to use 'systemctl restart' to reload profiles by doing full TuneD restart which can have some overhead.
- Switching of the TuneD profiles will work asynchronously, i.e. there will be no signalling that the profile is fully loaded/applied.
- The 'verification' feature will not work ('tuned-adm verify'), this feature compares current system setting with the active TuneD profile and reports found differences.

**Comment by maxpain** [comment]
Ok. I want to run TuneD as a DaemonSet in my Kubernetes cluster, and run like this `tuned --no-dbus -p network-latency`, so I don't need `tuned-adm`. Is it the right way in my case?

**Comment by yarda** [comment]
If you don't need to control it other way than just starting/stopping it should work. You could also switch TuneD profiles by directly writing to /etc/tuned/active_profile/profile_mode and restarting the TuneD daemon - it works, but is unsupported (we can change this control mechanism any time without prior notice).

For RHEL-9.2 we are going to also add socket interface (https://bugzilla.redhat.com/show_bug.cgi?id=2113900).

**Comment by maxpain** [comment]
Thank you!

Actually, I don't need to change profiles. And I use [Talos Linux](https://www.talos.dev/) for my Kubernetes cluster.
