### ISSUE TITLE
improvements on the tuned.service file

### ISSUE THREAD

**Issue by gfa** [redhat-performance/tuned#47]
Hello

this service file is better liked by lintian, I though it may be useful for rh/fedora too. I'm not sure about removing syslog.target  on those distros

[tuned.service.txt](https://github.com/redhat-performance/tuned/files/966598/tuned.service.txt)

thanks

**Comment by yarda** [comment]
Thanks, I think the syslog.target is not needed anymore. AFAIK log messages should be now processed by socket activated syslog or stored into journal.
