### ISSUE TITLE
[RFE] Support for negation "^" in the cpulist_unpack function

### ISSUE THREAD

**Issue by krsacme** [redhat-performance/tuned#49]
In OpenStack, some of the configuration support negation, like, having the cpu list as ["1-5", "^3"], should eventually add the list as "1,2,4,5". We have a scenario where we need to pass the same list of parameter to both OpenStack and tuned (tuned-profile-cpu-partitioning's isolated_cores). 

The expansion can be added at the caller, and it has to be added in multiple places. If it is done in the tuned it would be nice to have feature and has consistency.

**Comment by krsacme** [comment]
@yarda - would like to know your inputs?

**Comment by yarda** [comment]
Do you talk about  isolated_cores settings in cpu-partitioning-variables.conf? If yes, I think we could add support for negation into cpulist_unpack or cpulist_present Tuned built-in function. Maybe I would prefer '!' as negation, but it shouldn't be problem to support both syntaxes ('!' and '^'), e.g. the following:
`isolated_cores=2,4-7,!8`

**Comment by yarda** [comment]
Ah, it's clear from the subj. I am for it.

**Comment by krsacme** [comment]
Thanks @yarda. I should be able to raise a pull request by next week.
