### ISSUE TITLE
`powersave` profile should set epp to `power` or `balance_power`

### ISSUE THREAD

**Issue by ryanabx** [redhat-performance/tuned#563]
FYI: My system is an Asus ROG Zephyrus G14 GA402RJ with an AMD Ryzen 6900HS CPU

Hello, I'm new to using tuned and would like to suggest a change for better power savings.

When using the `powersave` profile in tuned, the energy_performance_preference defined in `/sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference` should be set to `balance_power` or for more strict configurations, `power`.

![image](https://github.com/redhat-performance/tuned/assets/56272643/ea60b043-79c6-459f-9f03-328f90973405)

**Comment by yarda** [comment]
Thanks.
