### ISSUE TITLE
Performance problem cased by tuned service(plugin_cpu.py)

### ISSUE THREAD

**Issue by sundyyuan** [redhat-performance/tuned#588]
Hi Dear,
       I met a problem during LAPACK workload(single core test) test with Ubuntu 20.04.6 LTS (Focal Fossa) +kernel 5.4.0-166. Non-busy core will switch C6 to C1E if tuned service was enabled with intel_idle driver, and non-busy core will always keep to C6 status if tuned service disabled.
       There has “tuned.plugins.plugin_cpu: setting new cpu latency 100” printed into /var/log/tuned/tuned.log with C6 switch to C1E. The related code(https://github.com/redhat-performance/tuned/blob/master/tuned/plugins/plugin_cpu.py) about the latency_low=100 from tuned.plugins. C6 latency is 170 in intel_idle driver, that less than 100 lead to non-busy core can’t keep C6 state. Is that a correct behavior from tuned.plugins? we expect all non-busy core is in C6 states to get a best performance.
      
Thanks
Sundy

**Comment by sundyyuan** [comment]
<img width="231" alt="intel_idle driver" src="https://github.com/redhat-performance/tuned/assets/37354220/80b15338-a201-4319-9ab1-5491992b318e">

**Comment by yarda** [comment]
Which TuneD profile? There are some low latency profiles which intentionally prevents CPU from entering deeper C-states for low latency (force_latency and pm_qos_resume_latency_us cpu plugin options).

**Comment by sundyyuan** [comment]
we set profile to throughput-performance, and I have tried change profile to powersave or balanced have the same behaviour. And can't enter C6 issue in non-busy core problem will lost if disable tuned service.

**Comment by yarda** [comment]
throughput-performance shouldn't touch it. Could you provide debug output?

```
# systemctl stop tuned
# tuned -D
```

**Comment by sundyyuan** [comment]
[
[tuned-D.txt](https://github.com/redhat-performance/tuned/files/14005610/tuned-D.txt)
](url)

**Comment by sundyyuan** [comment]
tuned -D output was upload.

**Comment by sundyyuan** [comment]
Non-busy will always keep C6 states after setting dynamic_tuning = 0 in /etc/tuned/tuned-main.conf and restart tuned service. So dynamic_tuning = 0 default setting will be changed in the newest tuned tool right?

**Comment by yarda** [comment]
> Non-busy will always keep C6 states after setting dynamic_tuning = 0 in /etc/tuned/tuned-main.conf and restart tuned service. So dynamic_tuning = 0 default setting will be changed in the newest tuned tool right?

We will probably unify the settings with RHEL/CentOS, i.e. we will switch to `dynamic_tuning = 0` in upstream, but there is no ETA for this change. In Fedora, if you change it yourself, the package manager will not overwrite your settings during updates.

**Comment by sundyyuan** [comment]
Thanks for your comment. We will manually set dynamic_tuning = 0 in Ubuntu at now.
