### ISSUE TITLE
starting tuned service fails on FedoraRawhide 41 

### ISSUE THREAD

**Issue by zhiqiangf** [redhat-performance/tuned#639]
[root@hpe-netqe-syn480g10-08 tuned]# cat /etc/redhat-release 
Fedora release 41 (Rawhide)

[root@hpe-netqe-syn480g10-08 ~]# rpm -aq | grep tuned
tuned-2.23.0-3.fc41.noarch
tuned-profiles-cpu-partitioning-2.23.0-3.fc41.noarch

[root@hpe-netqe-syn480g10-08 ~]# systemctl enable tuned && systemctl start tuned
Created symlink '/etc/systemd/system/multi-user.target.wants/tuned.service' → '/usr/lib/systemd/system/tuned.service'.
Job for tuned.service failed because a timeout was exceeded.
See "systemctl status tuned.service" and "journalctl -xeu tuned.service" for details.
[root@hpe-netqe-syn480g10-08 ~]# journalctl -xeu tuned.service
Jun 14 16:25:09 hpe-netqe-syn480g10-08.knqe systemd[1]: Starting tuned.service - Dynamic System Tuning Daemon...
░░ Subject: A start job for unit tuned.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit tuned.service has begun execution.
░░ 
░░ The job identifier is 2183.
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]: Exception in thread Thread-1 (_thread_code):
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]: Traceback (most recent call last):
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:   File "/usr/lib64/python3.13/threading.py", line 1039, in _bootstrap_inner
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:     self.run()
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:     ~~~~~~~~^^
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:   File "/usr/lib64/python3.13/threading.py", line 990, in run
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:     self._target(*self._args, **self._kwargs)
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:   File "/usr/lib/python3.13/site-packages/tuned/daemon/daemon.py", line 199, in _thread_code
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:     self._unit_manager.create(self._profile.units)
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:     ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:   File "/usr/lib/python3.13/site-packages/tuned/units/manager.py", line 112, in create
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:     instance.plugin.assign_free_devices(instance)
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:   File "/usr/lib/python3.13/site-packages/tuned/plugins/base.py", line 175, in assign_free_devices
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:     log.warn("instance %s: no matching devices available" % instance.name)
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:     ^^^^^^^^
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]: AttributeError: 'TunedLogger' object has no attribute 'warn'
Jun 14 16:25:55 hpe-netqe-syn480g10-08.knqe systemd[1]: tuned.service: start operation timed out. Terminating.
Jun 14 16:25:55 hpe-netqe-syn480g10-08.knqe systemd[1]: tuned.service: Failed with result 'timeout'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit tuned.service has entered the 'failed' state with result 'timeout'.
Jun 14 16:25:55 hpe-netqe-syn480g10-08.knqe systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
░░ Subject: A start job for unit tuned.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit tuned.service has finished with a failure.
░░ 
░░ The job identifier is 2183 and the job result is failed.

[root@hpe-netqe-syn480g10-08 ~]# systemctl status tuned.service
× tuned.service - Dynamic System Tuning Daemon
     Loaded: loaded (/usr/lib/systemd/system/tuned.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: timeout) since Fri 2024-06-14 16:25:55 EDT; 7min ago
 Invocation: 00a73bb89c064afd9140968335559550
       Docs: man:tuned(8)
             man:tuned.conf(5)
             man:tuned-adm(8)
    Process: 6087 ExecStart=/usr/sbin/tuned -l -P (code=exited, status=0/SUCCESS)
   Main PID: 6087 (code=exited, status=0/SUCCESS)

Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:   File "/usr/lib/python3.13/site-packages/tuned/units/manager.py", line 112, in create
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:     instance.plugin.assign_free_devices(instance)
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:   File "/usr/lib/python3.13/site-packages/tuned/plugins/base.py", line 175, in assign_free_devices
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:     log.warn("instance %s: no matching devices available" % instance.name)
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]:     ^^^^^^^^
Jun 14 16:25:10 hpe-netqe-syn480g10-08.knqe tuned[6087]: AttributeError: 'TunedLogger' object has no attribute 'warn'
Jun 14 16:25:55 hpe-netqe-syn480g10-08.knqe systemd[1]: tuned.service: start operation timed out. Terminating.
Jun 14 16:25:55 hpe-netqe-syn480g10-08.knqe systemd[1]: tuned.service: Failed with result 'timeout'.
Jun 14 16:25:55 hpe-netqe-syn480g10-08.knqe systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.
[root@hpe-netqe-syn480g10-08 ~]#

**Comment by adriaan42** [comment]
TuneD uses both `log.warning()` and the deprecated `log.warn()`, which was removed in Python 3.13.

From https://docs.python.org/3.13/library/logging.html:

> Changed in version 3.13: Remove the undocumented warn() method which was an alias to the [warning()](https://docs.python.org/3.13/library/logging.html#logging.warning) method.

I've just created https://github.com/redhat-performance/tuned/pull/640.

**Comment by yarda** [comment]
@zhiqiangf thanks for the report, @adriaan42 thanks for the fix.

**Comment by yarda** [comment]
Fixed by #640.
