### ISSUE TITLE
tuned crashing on startup

### ISSUE THREAD

**Issue by peterweissbier** [redhat-performance/tuned#670]
my tuned is crashing on system startup, the logs dont show much i think, but i added the logs and the systemctl status. i am on latest endeavourOS.

when i use systemctl start tuned and do a systemctl status then the program will work just fine, until i restart the computer.
[tuned.log](https://github.com/user-attachments/files/16570120/tuned.log)
[systemctl.md](https://github.com/user-attachments/files/16570122/systemctl.md)

**Comment by yarda** [comment]
I guess, it maybe conflict with `power-profiles-daemon`? Try:
```
# systemctl status power-profiles-daemon
```
If it's running, uninstall `power-profiles-daemon` and install `tuned-ppd` which is drop-in replacement using TuneD backend. In Fedora 41 `tuned-ppd` is the default PPD (https://fedoraproject.org/wiki/Changes/TunedAsTheDefaultPowerProfileManagementDaemon).

**Comment by peterweissbier** [comment]
ah yeah that was the problem, i removed power-profiled-daemon and installed tuned-ppd and it works now, thank you.

**Comment by yarda** [comment]
OK, thanks for the info, I am closing the ticket. Maybe it could be improved in packaging in your distro, e.g. by explicit package conflict or some notification.
