### ISSUE TITLE
Changing power profile with tuned-adm doesn't update GNOME widget

### ISSUE THREAD

**Issue by xChAmeLIoNz** [redhat-performance/tuned#714]
OS: Fedora 41
Gnome 47

I have a script setup as a user systemd service (`power_monitor.service`) that monitors and changes automatically the power profile when switching from AC to battery and viceversa.

To change the profile I use `tuned-adm` like this:
```
tuned-adm profile $profile
```
Where `$profile` can be `throughput-performance`, `balanced` and `powersave` for battery <20%

After changing the profile I restart with `systemctl` the services `tuned` and `tuned-ppd` without sudo using a custom polkit rule.

Here's the problem that annoys me: the Gnome power profile widget label from the dropdown menu doesn't change immediately but after some time (>5 minutes).

What I was able to notice is that if I restart the services manually outside the script, the label changes immediately. This also work if I don't use the polkit rule and I'm asked to authenticate when I run the script.

Is this a bug or am I missing something?

![Screenshot From 2024-11-29 20-21-13](https://github.com/user-attachments/assets/76f90f94-4fcb-4e2c-855d-dc43648e55d1)

**Comment by zacikpa** [comment]
Thank, @xChAmeLIoNz. I'll close this issue, since it duplicates #689, which should be resolved when #669 is merged.
