### ISSUE TITLE
tuned UEFI kernel boot params not set

### ISSUE THREAD

**Issue by sghosh151** [redhat-performance/tuned#81]
I have a custom tuned profile with the following content to enable IOMMU and SRIOV
But after running tuned-adm profile XXX, the sysfs changes take place, but /etc/grub2-efi.cfg shows no iommu updates. The include from /etc/grub/00_tuned is present - but that files content was not touched in the creation of the new profile.

CentOS7 / tuned-2.8.0-5.el7.noarch

consts.py only seems to support EFI: "redhat", "fedora" and BIOS, but no EFI "centos"
GRUB2_CFG_FILES = ["/boot/grub2/grub.cfg", "/boot/efi/EFI/redhat/grub.cfg", "/boot/efi/EFI/fedora/grub.cfg"]

#```
###############
[main]
summary=Optimize for running KVM guests and SR-IOV
include=virtual-host
#
## Add kernel option to enable IOMMU for device passthru in virt
#
[bootloader]
cmdline = "intel_iommu=on"
#
## Enable all vNICs on Intel I350 card
#
[sysfs]
/sys/class/net/enp1s0f0/device/sriov_numvfs=7
/sys/class/net/enp1s0f1/device/sriov_numvfs=7
###################

```

**Comment by olysonek** [comment]
Thanks for the report.

Perhaps we should only use the symlinks /etc/grub2.cfg and /etc/grub2-efi.cfg to edit the configuration and not touch the files under /boot/efi directly, in order to minimize the risk of editing other operating systems' configurations.

**Comment by olysonek** [comment]
You should be able to force the path to the configuration file using the "grub2_cfg_file" parameter under the [bootloader] section.

**Comment by olysonek** [comment]
Fixed by this pull request:
https://github.com/redhat-performance/tuned/pull/103
