### ISSUE TITLE
"tuned-adm list" outputs profile name with TYPO (?)

### ISSUE THREAD

**Issue by AdamKane41** [redhat-performance/tuned#93]
After running "tuned-adm list", the output reads: "[...] - through**P**ut-performance      - Broadly applicable tuning that provides excellent performance across a variety of common server workloads [...]"...

- Shouldn't it be "through**O**ut-performance" insted of "through**P**ut-performance"?

- Also, is the typo only present in the profile list or is it also the actual name of that profile (a.k.a. should I run "tuned-adm profile through**P**ut-performance" or "tuned-adm profile through**O**ut-performance")?

Thanks
(note that capitalized "p" and "o" are only here for emphasis and are not in actual  output)

**Comment by jeremyeder** [comment]
throughput is correct
